### ISSUE TITLE
Poor compilation performance due to linear lookup in scoped variables

### ISSUE THREAD

**Issue by fleupold** [JacobEberhardt/ZoKrates#102]
I noticed that compilation times for larger `.code` files easily become long and ran a profiler on the compilation step of a ZoKrates debug build.

```
valgrind --tool=callgrind --dump-instr=yes --collect-jumps=yes --simulate-cache=yes ./zokrates compile -i <code file>
```

Looking at the results, I noticed that almost 60% of the time is spent in [this line](https://github.com/JacobEberhardt/ZoKrates/blob/6ed8d6c86a03c9a0bda6a7ce98ff46a32fa584d4/src/semantics.rs#L237) `Iterator::find` called from `Checker::check_expression`.

```
self.scope.iter().find(|v| v.id.id == variable) { ... }
```

Given that `scope` is already of type `HashSet<ScopedVariable>`, I was wondering if we could use constant time lookup via the `get` function instead of looping of the entire iterator with find? We would have to implement `hash` and `eq` on `ScopedVariable` to match only on `id` rather than both `id` and `level`. 

Can you see a problem with this? Alternatively, would we somehow be able to predict the level of the variable we are looking for so that we could create a temporary `ScopedVariable` that matches the one in the `HashSet` (without creating custom `eq`, `hash` methods)?

I changed the code locally as suggested and noticed a dramatic reduction in CPU instructions (81 million -> 34 million) for my example. However, I'm not sure if I'm missing something here and am introducing a problem somewhere else.

Please find attached the .code file as well as profiling results for the original and optimised code. I'm happy so submit a pull request if there is no concern with changing this.

[issue.zip](https://github.com/JacobEberhardt/ZoKrates/files/2274298/issue.zip)

**Comment by Schaeff** [comment]
Awesome thanks, let me see :)

**Comment by Schaeff** [comment]
I don't see a problem with the approach. I don't think creating the `ScopedVariable` to match would work as it could have any scope.

I'm not sure a custom Hash trait would be the best way to solve, I'm thinking to rather refactor `scope` to hold a `HashMap<String, ScopedVariable>` and use `get`

Any thoughts?

**Comment by Schaeff** [comment]
Hey @fleupold any chance you could run your tests on https://github.com/Schaeff/ZoKrates/tree/constant-time-scope ? Also welcome thoughts on the changes there :)

Indexing the scope per level as well would be good as we need to remove all variables for a given level, let me see if you see a big performance impact?

**Comment by fleupold** [comment]
Thanks for the quick turnaround. I commented on the branch.
I'm not sure I fully understand the stack approach. Would you still have a map on top of the stack or would you be able to get constant time access for both properties with the same data structure?

**Comment by Schaeff** [comment]
I'm not sure, let's focus on access to variables and keep deletion from scope for another issue :)
Answered there

**Comment by Schaeff** [comment]
Merged
