### ISSUE TITLE
Feature request: Count constraints

### ISSUE THREAD

**Issue by nicola** [JacobEberhardt/ZoKrates#11]
Is there a command to count the number of constraints generated?
or other insights about the circuit?

**Comment by nicola** [comment]
I just saw that the setup shows them:

```
num variables: 4
num constraints: 2
num inputs: 2
Swap is not beneficial, not performing
* QAP number of variables: 3
* QAP pre degree: 2
* QAP degree: 5
* QAP number of input variables: 2
* G1 window: 3
* G2 window: 1
* G1 elements in PK: 38
* Non-zero G1 elements in PK: 25
* G2 elements in PK: 5
* Non-zero G2 elements in PK: 2
* PK size in bits: 7841
* G1 elements in VK: 4
* G2 elements in VK: 5
* VK size in bits: 3948
```

Is it possible to have some of those details on compilation - or am I getting something wrong?

**Comment by JacobEberhardt** [comment]
This information is readily available, as it is the number of lines in the human readable .code file the compiler outputs.
However, I can explicitly display it after compilation.
Would you want to have it as simple output in the terminal?

**Comment by JacobEberhardt** [comment]
Added as console output.

**Comment by nicola** [comment]
Awesome!
