### ISSUE TITLE
Setup runtime grows quadratic with number of variables

### ISSUE THREAD

**Issue by fleupold** [JacobEberhardt/ZoKrates#120]
I believe this code is causing the setup step to run in quadratic time with number of variables.

https://github.com/JacobEberhardt/ZoKrates/blob/de577383775d1fa3fa4165e92d08010aab16347f/zokrates_core/src/r1cs.rs#L247-L261

Would it be possible to replace the Vector with a more efficient data-structure, e.g. a HashMap of `vName->index` combined with a `nextIndex` or something alike?

Please find callgrind performance traces attached (variables: 10108, constraints: 39264, inputs: 1).

<img width="1632" alt="screen shot 2018-09-03 at 16 36 09" src="https://user-images.githubusercontent.com/1200333/44992461-8f115380-af97-11e8-85cd-18052c792b7c.png">

[callgrind.out.setup-step.zip](https://github.com/JacobEberhardt/ZoKrates/files/2345887/callgrind.out.setup-step.zip)

**Comment by Schaeff** [comment]
Hey @fleupold thanks for this, it does look like something that could be optimised. Did you identify a solution you're confident with? We'd welcome a PR on this if so :)

**Comment by Schaeff** [comment]
Merged, closing!
