### ISSUE TITLE
Error in witness computation using optimized code

### ISSUE THREAD

**Issue by bonfiley** [JacobEberhardt/ZoKrates#121]
After using --optimized compiler option, I get the following error while computing witness.  The code works fine when --optimized is not used.

thread 'main' panicked at 'no entry found for key', libcore/option.rs:960:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:511
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:426
   6: rust_begin_unwind
             at libstd/panicking.rs:337
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:92
   8: core::option::expect_failed
             at libcore/option.rs:960
   9: <zokrates_core::flat_absy::FlatExpression<T>>::solve
  10: <zokrates_core::flat_absy::FlatExpression<T>>::solve
  11: <zokrates_core::flat_absy::FlatFunction<T>>::get_witness
  12: zokrates::main
  13: std::rt::lang_start::{{closure}}
  14: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  15: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  16: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:374
             at libstd/rt.rs:58
  17: main
  18: __libc_start_main
  19: <unknown>
../Makefile:26: recipe for target 'witness' failed

**Comment by Schaeff** [comment]
Hi @bonfiley thanks for this could you update the issue with the code you were compiling?

**Comment by Schaeff** [comment]
Closing this as we've made changes to the optimizer. Thanks for sharing this @bonfiley , do open again if you can reproduce
