### ISSUE TITLE
Intermediate representation for ZoKrates - portable circuits

### ISSUE THREAD

**Issue by HarryR** [JacobEberhardt/ZoKrates#124]
The jsnark project uses an intermediate assembly-ish language to allow the circuits to be imported into libsnark:

 * https://github.com/akosba/libsnark/blob/fde8599fc047e9d681ee8f8325913c76de389b55/src/interface/CircuitReader.cpp
 * https://github.com/akosba/libsnark/blob/fde8599fc047e9d681ee8f8325913c76de389b55/src/interface/run_libsnark.cpp

Example:
```
input 0
input 1
nizkinput 3
nizkinput 4
nizkinput 5
output 6
add <3 4> out 0
mul <0 4> out 1
...
``` 

Opcodes:
 * add
 * mul
 * or
 * xor
 * zerop
 * split
 * const-mul-neg-
 * const-mul-
 * pack
 * assert

The JSnark circuit builder outputs to this format, and the xjsnark high-level language uses JSNark - and such compiles down to these opcodes.

I think opcodes like this are *much* simpler than the suggestions so far involving WebAssembly and JSON, because they can be quickly implemented and emulated over any field. So it can act as a portable format that both ZoKrates and JSnark could both compile to. Additionally it could serve as a uniform representation for circuits across Bellman and libsnark backends.

 * jsnark - https://github.com/akosba/jsnark
 * xjsnark - https://github.com/akosba/xjsnark

However, a problem is witness generation. Say there is the difference between user-input and intermediate variables, from the user input the intermediate variables must be calculated.

Secondly @Schaeff mentioned function support, where the 2nd stage would inline all of the functions to produce the final circuit.

example:
```
input 0
input 1
output 2

def x(a, b):
  assembly:
    local c
    add c a b
  return $c

call x(0, 1) 2
```

Translates to
```
input 0
input 1
output 2
add 2 <0 1> out 1 <2>
```

It would be nice to be able to support jsnark output as-is, but with a function layer ontop of it.

A compact binary representation could be something like:

 * `uint8` - optype
 * `uint32` - arg 1
 * `uint32` - arg 2
 * ...

Where optype decides how many arguments are necessary?

**Comment by Schaeff** [comment]
Closing this as we agreed to explore a more generic approach, based on wasm.
