### ISSUE TITLE
Dynamic scoping

### ISSUE THREAD

**Issue by Schaeff** [JacobEberhardt/ZoKrates#16]
Consider the following program:
```
def foo():
  a = b + 5
  return a

def bar():
  b = 2
  return foo()

def main(): 
  return bar()
```
Currently, it compiles and runs, returning 7. This means that in `foo`, `b` exists even though it's declared in `bar`. Scope is determined based on the execution (when `foo` is executed, we're in `bar` which defined `b`) not how the functions are defined (in the context of the definition of `foo`, `b` is not defined)

I'm not suggesting that this is a bug: some languages like Perl use dynamic scoping. However, a large majority uses static scoping (based on definitions, not execution) and that's what most developers would expect. I guess the questions could be:

- Does ZoKrates benefit from dynamic scoping?
- What would switching to static scoping involve?

Any feedback?

References:
[https://msujaws.wordpress.com/2011/05/03/static-vs-dynamic-scoping/](https://msujaws.wordpress.com/2011/05/03/static-vs-dynamic-scoping/)

**Comment by curlysemi** [comment]
I suspect this was not an intentional language design decision. IMO, this is a symptom of the current approach to flattening. I have a local branch (that I hope to be submitting a PR for relatively soon—too many projects, too little time!) that changes the approach to symbol flattening. I think the changes I am working with result in static scoping. I'll run your example code sometime soon and post the results.

**Comment by curlysemi** [comment]
Yeah, I'm getting 7, so it looks like there's somewhere in the flattening code I need to tweak still. (Wasn't originally considering this case, as the complex code I'm adjusting the flattening to was coded in a cautious style that is currently doing everything as public inputs.)

For the curious, this is the flattened code produced by my (still-in-development) flattener adjustments:
```
def foo():
        a = (b + 5)
        return a
def bar():
        b = 2
        foo_0_a = (b + 5)
        return foo_0_a
def main():
        bar_0_b = 2
        bar_0_foo_0_a = (bar_0_b + 5)
        return bar_0_foo_0_a
```
Clearly, the 'incorrect' line is `foo_0_a = (b + 5)` ('incorrect' from a static scoping perspective). I'll get this fixed before I submit my PR. The PR should also close issue #7.

**Comment by Schaeff** [comment]
Thanks for this @curlysemi! One implication of this I believe is that arguments to `main` cannot be considered global (they are in the dynamic sense as `main` is the first function called). So to pass arguments around in a static world we would need either functions defined in functions (not on the roadmap), or a functional style for programs, where the only scope is the function's arguments (just a change in programming style).

```
def main(a, b):
   def foo():
      return a + b
   return foo()
```
vs
```
def foo(a, b):
   return a + b
def main(a, b):
   return foo(a, b)
```

**Comment by Schaeff** [comment]
@JacobEberhardt I believe we can close this now?

**Comment by JacobEberhardt** [comment]
Agreed!
