### ISSUE TITLE
Verifiying a SHA256

### ISSUE THREAD

**Issue by nicola** [JacobEberhardt/ZoKrates#2]
Hey @JacobEberhardt awesome work,
I look forward to see this being used and reached production level.

- I was wondering how would I go about proving knowing the pre-image of a sha256?
- Should I re-implement sha256 in.. `.code`?
- Is it possible to have it as "gadget" and have a much simpler language than directly using C in libsnark?

**Comment by JacobEberhardt** [comment]
Thanks for your input, hash functions didn't make it into this research prototype yet.

In the future, I would like to provide a library for functions relevant to the domain, such as hashing, signing etc.. Then, you could simply use these functions in your '.code' files.

For now, you would have to re-implement it yourself. I'd of course be happy about contributions ;)

**Comment by nicola** [comment]
Please if you have directions for me or others that are interested in attempting, where and how they should look into. I think integrating hash functions is going to be quite essentials (see the latest ZKCSP paper)!

**Comment by JacobEberhardt** [comment]
I created a Gitter Channel, so we can communicate more easily:
https://gitter.im/ZoKrates/Lobby

I think this will also be a good place to discuss contributions.

**Comment by nicola** [comment]
(thanks @JacobEberhardt community will reveal to be the most important factor for success here^)

**Comment by nicola** [comment]
What are the easiest next steps to get this integrated?

Here is my proposal:
- Compile SHA256 from libsnark into an R1CS
- Extract flattened code from R1CS
- Allow for importing r1cs from a different file

**Comment by HarryR** [comment]
Hi @nicola - I've implemented a zkSNARK circuit using libsnark to verify the preimage of a SHA256 without revealing the preimage.

I'm working on it on the `solidity` branch of https://github.com/HarryR/ethsnarks - currently sorting some issues out with packing uint256s to 253 bit words in F_p etc. however, the aim is to have a set of native libraries which can be used to generate the proofs, and a set of Solidity libraries to make it easy to verify proofs (preferably using ABIEncodingV2, to make life simpler for developers).

Watch this space... etc. etc.

**Comment by Schaeff** [comment]
I think we now have the tools to do this, cf https://github.com/JacobEberhardt/ZoKrates/blob/develop/zokrates_cli/tests/code/sha_libsnark_packed.code so I'm closing
