### ISSUE TITLE
Feature request: Some sort of multiple return

### ISSUE THREAD

**Issue by PeterBorah** [JacobEberhardt/ZoKrates#4]
I'm currently attempting to implement SHA-256, and in order to do this I need to work on 32-bit words. Right now functions can only return a single value, making it impossible to encapsulate operations on these 32-bit words.

The two good solutions I can think of:

1) There could be some sort of basic fixed-length array/tuple type, which would be a valid return type. (This is ideal, but I don't know how hard it's likely to be.)

```
def duplicate(x):
    return [x, x]

def main(x):
    y = duplicate(x)
    y[0] == x
    y[1] == x
```

2) Functions could be allowed to return multiple values, with required destructuring assignment:

```
def duplicate(x):
    return x, x

def main(x):
    y, z = duplicate(x)
    y == x
    z == x
```

There are also less elegant solutions:

3) Global variables could be used to store state.
```
y = 0
z = 0

def duplicate(x):
    y = x
    z = x

def main(x): 
    duplicate(x)
    y == x
    z == x
```

4) There could be a macro system that inserted code in a way that allowed intentional shadowing.

```
macro duplicate():
    y = x
    z = x

def main(x): 
    y = 0
    z = 0
    duplicate()
    y == x
    z == x
```

**Comment by JacobEberhardt** [comment]
Peter, thank you so much for your input! I will look into what i can most efficiently support and implement that.

**Comment by JacobEberhardt** [comment]
@Schaeff implemented the second proposal in #18.
We are still discussing internal structure, but it already works.

**Comment by JacobEberhardt** [comment]
I'll leave this open until we finalized internal structure and merged into develop.

**Comment by Schaeff** [comment]
Merged into develop
