### ISSUE TITLE
Unable to use the exported smart contract

### ISSUE THREAD

**Issue by lovesh** [JacobEberhardt/ZoKrates#50]
I am using truffle to export the generated smart contract for [factorization.code](https://github.com/JacobEberhardt/ZoKrates/blob/develop/examples/factorization.code). Versions
```
Truffle v4.1.5 (core: 4.1.5)
Solidity v0.4.21 (solc-js)
```
I am able to compile (with warning though but are addressed here https://github.com/JacobEberhardt/ZoKrates/pull/49) and deploy the contract but when i try to test it, i get error
```
...../contracts/Verifier.sol:1
(function (exports, require, module, __filename, __dirname) { pragma solidity ^0.4.14;
```
The test is [here](https://gist.github.com/lovesh/4d2b12fb3f90f7e9c2fa8b5885928adf) and the contract is [here](https://gist.github.com/lovesh/1d5ca53de66a4423918763a392450677)  

Also i don't understand which contracts are being called at
https://github.com/lovesh/ZoKrates/blob/develop/src/verification.rs#L49, 
https://github.com/lovesh/ZoKrates/blob/develop/src/verification.rs#L64 and 
https://github.com/lovesh/ZoKrates/blob/develop/src/verification.rs#L91

As i understand, the second argument to `call` is supposed to be contract address, but they don't seem like contract address, are they? If yes, then can you please point me to those contracts or relevant sections of solidity documentation. 
Thanks

**Comment by Schaeff** [comment]
They are indeed contract addresses, more precisely the precompiles introduced during the Byzantium HF, see ethereum/EIPs/blob/master/EIPS/eip-196.md and ethereum/EIPs/blob/master/EIPS/eip-197.md and which introduce precompiles at `0x6`, `0x7`, `0x8`,

**Comment by Schaeff** [comment]
Closing for #42 @lovesh can you check quotes resolves this?

**Comment by lovesh** [comment]
@Schaeff No, it does not. I updated that issue with more details.

**Comment by lovesh** [comment]
@Schaeff Thanks. I did not realize that since the code did not reach till there

**Comment by Schaeff** [comment]
@lovesh let me know if I can close this?

**Comment by lovesh** [comment]
@Schaeff I havent spent anymore time on this, i should be able to get back to it in a 2 days

**Comment by Schaeff** [comment]
Ok I'll assume this is fixed, do open a new issue if you're still stuck!
