### ISSUE TITLE
Possible Less-Than Operator Issue?

### ISSUE THREAD

**Issue by curlysemi** [JacobEberhardt/ZoKrates#7]
Hello,

I've been playing with this toolbox for a few days and am attempting some somewhat complex code, but I have ran into some strange behavior when using the the less-than operator.

The issue doesn't arise when the code is simple. An example starting point:

```
def lt(a,b):
    return if a < b then 1 else 0 fi

def main():
    return lt(31337, 2197)
```

As expected, the returned value when `main()` is called is `0`.

A minor note (mostly for my own sanity): we can make a slight adjustment and get the same result:
```
def lt(a,b):
    return if a < b then 1 else 0 fi

def cutoff():
    return 31337

def main():
    return lt(cutoff(), 2197)
```

Now, let's introduce some slight complexity, allowing `31337` to be compared to another value—a value that is computationally arrived upon based off of an input:
```
def getThing(index):
    result = 3
    result = if index == 0 then 13 else result fi
    result = if index == 1 then 23 else result fi
    result = if index == 2 then 43 else result fi
    result = if index == 3 then 53 else result fi
    result = if index == 4 then 73 else result fi
    result = if index == 5 then 83 else result fi
    return result

def cubeThing(thing):
    return thing**3

def main(index):
    thing = getThing(index)
    thing = cubeThing(thing)
    return thing
```

We can call our new `main()` function with an argument of `0`, and the returned value is `2197`. So far so good.

Things seem to go awry when we try to combine our new stuff with the old stuff:

```
def lt(a,b):
    return if a < b then 1 else 0 fi

def cutoff():
    return 31337

def getThing(index):
    result = 3
    result = if index == 0 then 13 else result fi
    result = if index == 1 then 23 else result fi
    result = if index == 2 then 43 else result fi
    result = if index == 3 then 53 else result fi
    result = if index == 4 then 73 else result fi
    result = if index == 5 then 83 else result fi
    return result

def cubeThing(thing):
    return thing**3

def main(index):
    thing = getThing(index)
    thing = cubeThing(thing)
    return lt(cutoff(), thing)
```
This most recent `main()` is the mostly the same as the previous one that yielded `2197`. The only difference between this new code and the previous is that, instead of returning the value, we compare `31337` to the value (just as in the *very* first example). When we call this newest `main()` with an argument of `0`, we get an unexpected result!
```
Returned (~out): 1
```
It's telling us that 31337 is less than 2197! It seems that no matter the input to this code, the resulting value is `1`. I have no idea what's happening. :) I suppose my question is: is there an issue with this code, or with ZoKrates itself?

Thanks,
—J

**Comment by JacobEberhardt** [comment]
Thank you for the report, I'll look into it. The code looks fine, so I assume it is an internal issue for now.

**Comment by Schaeff** [comment]
We're making progress on this with the new flattening approach https://github.com/JacobEberhardt/ZoKrates/commit/8e7197438f954a64bfd3bca592bb46b34e07babb

**Comment by Schaeff** [comment]
@JacobEberhardt Let's check if this is fixed, I guess this now would fail due to binary function calls bug #43 but could be fixed by #56

**Comment by lubieplacki** [comment]
See: https://github.com/JacobEberhardt/ZoKrates/issues/43#issuecomment-389115857

**Comment by JacobEberhardt** [comment]
fixed by @lubieplacki
