### ISSUE TITLE
Implement BLS12-381 precompile

### ISSUE THREAD

**Issue by axic** [JacobEberhardt/ZoKrates#90]
@Schaeff has explained to me that the new BLS12-381 curve seems to be much faster for pairing and that the ZCash team has creating a new library in Rust for it: https://github.com/zkcrypto/pairing

It would be nice to figure out if that is true, but unfortunately it would require a new precompile on the mainnet.

However, since thee pairing library is in Rust and the ewasm project has current mainnet precompiles rewritten in Rust (https://github.com/ewasm/ewasm-precompiles) I think it would be extremely simple to compile the new pairing library and have it supported on the ewasm testnet.

I think this would be a really good opportunity to test these assumptions while utilising the ewasm testnet without a lot of effort put into it.

**Comment by axic** [comment]
After a tiny fix to ebfull/ff I could compile zkcrypto/pairing for the `wasm32-unknown-unknown` target.

**Comment by axic** [comment]
With rustc >=1.27 this compiles properly, no upstream changes needed. Need to define the data format for the precompile and then it should be good to go.

**Comment by Schaeff** [comment]
Hi @axic I just pushed an MVP of the BLS12 pairing here https://github.com/Schaeff/ethereum-bls12.rs check it out

**Comment by Schaeff** [comment]
Just updating before I close: 
- BLS12-381 is not faster. See [here](https://blog.z.cash/new-snark-curve/) for the design goals behind it.
- The prototype now lives in the ewasm org https://github.com/ewasm/ethereum-bls12.rs

**Comment by MichaelConnorOfficial** [comment]
Hi @Schaeff , I'm surprised that BLS12-381 wasn't faster than the alt_BN128 curve. Was there no improvement in speed at all?
I've been looking into whether it's worth working on a BLS12-381 / jubjub c++ library for libsnark (to then use in ZoKrates), but it would only be worthwhile at the moment if using BLS12-381 would reduce time and gas costs. If all it improves is security I'd be less inclined to work on it.

I'd be interested to hear your thoughts? :)

Was it just pairings that were tested? I'd have thought there would be significant time improvements in double and add operations, given that jubjub uses twisted Edwards curve group operations which are faster than the segmented Weierstrass curve group operations. Are twisted Edwards operations not proving to be faster in practice?
