### ISSUE TITLE
Unexpected result for < operator

### ISSUE THREAD

**Issue by fleupold** [JacobEberhardt/ZoKrates#99]
I'm probably lacking some mathematical background here, but I was surprised to see that the following program

```
def main():
  return if 0 < 21888242871839275222246405745257275088548364400416034343698204186575808495616 then 1 else 0 fi
```

returns 0. I would have expected it to return 1, since 0 should be smaller than the large number. 

Does this have something to do with interpreting the larger number as a signed integer (-1)? If so, where would be the "underflow point" for which i < i-1?

I'm trying to write a proof that is dealing with potentially very large unsigned integers and would like to know what the highest number `n` is, for which `0 < n`.

**Comment by fleupold** [comment]
Could you point me to the code/theory of how `<` flattening works? What's the largest number that I can safely assume to be > 0?

**Comment by Schaeff** [comment]
We're going to release a patch that makes this stricter so you can't go wrong. I'll link the patch and the approach here.

**Comment by Schaeff** [comment]
Fix merged, let me know @fleupold, closing this, thanks!

**Comment by Schaeff** [comment]
Sorry wrong issue, reopening until #104 is merged
